# Configuration spécifique pour Vercel
baseurl: ""
url: "https://site-franchini.vercel.app"

# Désactiver le cache pour le développement
cache_buster: false

# Activer la compression GZIP
gzip: true

# Activer la génération de sitemap
sitemap:
  sitemap_style_xsl: false
  priority: 0.8
  changefreq: 'weekly'
