# Configuration de base pour RuboCop

# Désactiver tous les cops par défaut
AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 3.1

# Activer uniquement les cops importants
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
  Description: 'Add the frozen_string_literal comment to the top of files to help with string memory allocation.'

Layout/EmptyLineAfterMagicComment:
  Enabled: true
  Description: 'Add an empty line after magic comments.'

Layout/EmptyLinesAroundBlockBody:
  Enabled: true
  Description: 'Add empty lines around block bodies.'

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  Description: 'Add empty lines around class bodies.'

Layout/EmptyLinesAroundModuleBody:
  Enabled: true
  Description: 'Add empty lines around module bodies.'

Layout/EmptyLinesAroundMethodBody:
  Enabled: true
  Description: 'Add empty lines around method bodies.'

Layout/EmptyLineAfterGuardClause:
  Enabled: true
  Description: 'Add empty line after guard clause.'

Layout/EmptyLineBetweenDefs:
  Enabled: true
  Description: 'Add empty line between method definitions.'

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
  Description: 'Add empty lines around access modifiers.'

Layout/EmptyLinesAroundBeginBody:
  Enabled: true
  Description: 'Add empty lines around begin bodies.'

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: true
  Description: 'Add empty lines around exception handling keywords.'

Layout/EmptyLinesAroundMethodBody:
  Enabled: true
  Description: 'Add empty lines around method bodies.'

Layout/EmptyLinesAroundModuleBody:
  Enabled: true
  Description: 'Add empty lines around module bodies.'

Layout/EmptyLines:
  Enabled: true
  Description: 'Add empty lines around bodies of conditionals, classes, modules, methods, etc.'

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  Description: 'Add empty lines around class bodies.'

Layout/EmptyLinesAroundBlockBody:
  Enabled: true
  Description: 'Add empty lines around block bodies.'

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
  Description: 'Add empty lines around access modifiers.'

Layout/EmptyLinesAroundBeginBody:
  Enabled: true
  Description: 'Add empty lines around begin bodies.'

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: true
  Description: 'Add empty lines around exception handling keywords.'

Layout/EmptyLinesAroundMethodBody:
  Enabled: true
  Description: 'Add empty lines around method bodies.'

Layout/EmptyLinesAroundModuleBody:
  Enabled: true
  Description: 'Add empty lines around module bodies.'

Layout/EmptyLines:
  Enabled: true
  Description: 'Add empty lines around bodies of conditionals, classes, modules, methods, etc.'

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  Description: 'Add empty lines around class bodies.'

Layout/EmptyLinesAroundBlockBody:
  Enabled: true
  Description: 'Add empty lines around block bodies.'

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
  Description: 'Add empty lines around access modifiers.'

Layout/EmptyLinesAroundBeginBody:
  Enabled: true
  Description: 'Add empty lines around begin bodies.'

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: true
  Description: 'Add empty lines around exception handling keywords.'

Layout/EmptyLinesAroundMethodBody:
  Enabled: true
  Description: 'Add empty lines around method bodies.'

Layout/EmptyLinesAroundModuleBody:
  Enabled: true
  Description: 'Add empty lines around module bodies.'

Layout/EmptyLines:
  Enabled: true
  Description: 'Add empty lines around bodies of conditionals, classes, modules, methods, etc.'

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  Description: 'Add empty lines around class bodies.'

Layout/EmptyLinesAroundBlockBody:
  Enabled: true
  Description: 'Add empty lines around block bodies.'

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
  Description: 'Add empty lines around access modifiers.'

Layout/EmptyLinesAroundBeginBody:
  Enabled: true
  Description: 'Add empty lines around begin bodies.'

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: true
  Description: 'Add empty lines around exception handling keywords.'

Layout/EmptyLinesAroundMethodBody:
  Enabled: true
  Description: 'Add empty lines around method bodies.'

Layout/EmptyLinesAroundModuleBody:
  Enabled: true
  Description: 'Add empty lines around module bodies.'

Layout/EmptyLines:
  Enabled: true
  Description: 'Add empty lines around bodies of conditionals, classes, modules, methods, etc.'

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  Description: 'Add empty lines around class bodies.'

Layout/EmptyLinesAroundBlockBody:
  Enabled: true
  Description: 'Add empty lines around block bodies.'

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
  Description: 'Add empty lines around access modifiers.'

Layout/EmptyLinesAroundBeginBody:
  Enabled: true
  Description: 'Add empty lines around begin bodies.'

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: true
  Description: 'Add empty lines around exception handling keywords.'

Layout/EmptyLinesAroundMethodBody:
  Enabled: true
  Description: 'Add empty lines around method bodies.'

Layout/EmptyLinesAroundModuleBody:
  Enabled: true
  Description: 'Add empty lines around module bodies.'

Layout/EmptyLines:
  Enabled: true
  Description: 'Add empty lines around bodies of conditionals, classes, modules, methods, etc.'

# Désactiver les métriques de complexité
Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# Désactiver les métriques de style
Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SymbolArray:
  Enabled: false

# Configuration pour les fichiers spécifiques
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'Guardfile'
    - 'spec/**/*'
    - 'test/**/*'
    - 'features/**/*'
    - 'config.ru'
    - 'Gemfile'
    - 'Capfile'
    - 'config/environments/*.rb'
    - 'config/initializers/*.rb'
    - 'db/*.rb'
    - 'db/migrate/*.rb'
    - 'db/seeds.rb'
    - 'lib/tasks/*.rake'
    - 'tmp/**/*'
