# Configuration pour GitHub Pages
url: "https://Cedric-F-26.github.io"  # Remplacez par votre nom d'utilisateur GitHub
baseurl: "/Site-franchini"  # Le nom de votre dépôt

timezone: Europe/Paris

# Configuration de Jekyll
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .github/
