# Configuration de base
title: Franchini - Concessionnaire Deutz-Fahr
email: contact@franchini.fr
baseurl: ""
url: "https://franchini.fr"

# Configuration de sortie
destination: ./public

# Paramètres de construction
markdown: kramdown

# Permaliens
permalink: pretty

# Désactiver les trucs inutiles pour Vercel
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .bundle
  - .git
  - .gitignore
  - README.md
  - Rakefile
  - package.json
  - package-lock.json
  - _site
  - public
