sass:
  style: compressed
  sass_dir: _sass
  sourcemap: never
  quiet_deps: true
  verbose: false
  trace_selectors: false
  line_comments: false
  future_deprecation: false
  default_sass_import_path: _sass
  load_paths:
    - _sass
    - node_modules
