# Configuration pour GitHub Pages
baseurl: "/mon-site-web"  # Nom du dépôt GitHub
url: "https://cedric-f-26.github.io"  # URL de votre site GitHub Pages

# Configuration pour GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-minifier

# Configuration pour jekyll-assets
assets:
  sources:
    - _assets/images
    - _assets/fonts
    - _assets/js
    - _assets/css
  compress:
    css: true
    js: true
  cache: false
  gzip: [.css, .js, .svg, .eot, .ttf, .woff, .woff2]
  cache_path: "_cache"
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true
  assets: []
  features:
    automatic_img_size: true
    automatic_img_alt: true
    automatic_img_loading: true
    automatic_img_srcset: true
    automatic_img_sizes: true
    automatic_img_loading: true
    automatic_img_alt: true
    automatic_img_title: true
    automatic_img_class: true
    automatic_img_id: true
    automatic_img_loading: true
    automatic_img_decoding: true
    automatic_img_importance: true
    automatic_img_ismap: true
    automatic_img_loading: true
    automatic_img_referrerpolicy: true
    automatic_img_sizes: true
    automatic_img_srcset: true
    automatic_img_style: true
    automatic_img_usemap: true
    automatic_img_width: true
    automatic_img_height: true

# Paramètres du site
title: Franchini - Concessionnaire Deutz-Fahr
description: Concessionnaire officiel Deutz-Fahr - Matériel agricole neuf et d'occasion
email: contact@franchini.fr
language: fr

# Paramètres de construction
markdown: kramdown
theme: minima

# Activer le support pour les fichiers HTML
include:
  - _pages
  - _includes
  - _layouts
  - _sass
  - assets
  - .htaccess
  - CNAME
  - robots.txt
  - sitemap.xml

# Exclure les fichiers et dossiers inutiles
exclude:
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - .gitignore
  - .github/
  - .vscode/
  - .git/

# Configuration des chemins
destination: _site
plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
collections_dir: _collections

# Configuration pour les fichiers statiques
static_files:
  - assets/css/:/css/
  - assets/js/:/js/
  - assets/images/:/images/
  - assets/fonts/:/fonts/
  - assets/downloads/:/downloads/

# Configuration pour les marques et modèles
brands:
  - name: Deutz-Fahr
    logo: /assets/images/brands/deutz-fahr.png
    url: /marques/deutz-fahr
  - name: Stoll
    logo: /assets/images/brands/stoll.png
    url: /marques/stoll
  - name: Kramp
    logo: /assets/images/brands/kramp.png
    url: /marques/kramp
  - name: Kverneland
    logo: /assets/images/brands/kverneland.png
    url: /marques/kverneland

# Configuration pour les réseaux sociaux
social_links:
  - name: Facebook
    url: https://www.facebook.com/Franchini26300
    icon: facebook
  - name: Instagram
    url: https://www.instagram.com/franchini_agricole
    icon: instagram
  - name: YouTube
    url: https://www.youtube.com/user/FranchiniAgricole
    icon: youtube
  - name: LinkedIn
    url: https://www.linkedin.com/company/franchini-agricole
    icon: linkedin

# Paramètres de permaliens (pour des URLs propres)
permalink: pretty

# Paramètres de build
future: true
incremental: false

# Paramètres de temps
timezone: Europe/Paris

# Configuration des collections
collections:
  pages:
    output: true
    permalink: /:path/

# Exclure des fichiers de la construction
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - .git
  - README.md
  - Serveur.txt
  - vercel.json
  - netlify.toml
  - update-*.js
  - insert-*.js

# Inclure les fichiers et dossiers qui commencent par un point
include:
  - .htaccess
  - .nojekyll
  - robots.txt
  - sitemap.xml

# Configuration pour sitemap
sitemap:
  exclude:
    - "/assets/"
    - "/js/"
    - "/css/"
    - "/images/"

# Configuration SEO par défaut
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      sitemap: true

# Configuration pour les liens de navigation
navigation:
  - title: Accueil
    url: /
  - title: Neuf
    url: /pages/neuf/
  - title: Occasions
    url: /pages/occasion/
  - title: Services
    url: /pages/services/
  - title: Contact
    url: /pages/contact/

# Configuration du pied de page
footer:
  contact:
    address: "111 av des monts du matin, 26300 Marches"
    phone: "04 75 47 40 37"
    email: "contact@franchini.fr"
  social_links:
    - name: Facebook
      url: "#"
      icon: "fab fa-facebook-f"
    - name: Twitter
      url: "#"
      icon: "fab fa-twitter"
    - name: Instagram
      url: "#"
      icon: "fab fa-instagram"
    - name: LinkedIn
      url: "#"
      icon: "fab fa-linkedin-in"

# Configuration des métadonnées pour les réseaux sociaux
social:
  name: Franchini
  links:
    - "https://www.facebook.com/franchini"
    - "https://twitter.com/franchini"
    - "https://www.instagram.com/franchini"

# Configuration du thème (couleurs, polices, etc.)
theme:
  primary_color: "#4CAF50"
  secondary_color: "#2E7D32"
  accent_color: "#8BC34A"
  text_color: "#333333"
  light_text: "#757575"
  background: "#FFFFFF"
  font_family: "'Roboto', sans-serif"
  font_size: "16px"
  line_height: "1.6"

# Configuration des paramètres de développement
dev:
  minify: false
  cache: false
  verbose: true
    - "/admin/"
    - "/includes/"

# Configuration pour SEO
seo:
  name: Franchini
  social:
    name: Franchini
    links:
      - https://www.facebook.com/
      - https://twitter.com/
      - https://www.instagram.com/

# Configuration personnalisée
social_links:
  - platform: facebook
    url: https://www.facebook.com/
  - platform: twitter
    url: https://twitter.com/
  - platform: instagram
    url: https://www.instagram.com/

# Paramètres de navigation par défaut
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "assets"
    values:
      layout: null
  - README.md

# Configuration du thème (si vous en utilisez un)
theme: jekyll-theme-minimal

# Paramètres personnalisés
github:
  is_project_page: true
