# Modification de configuration pour forcer un build Vercel
# ==============================================================================
# CONFIGURATION DE BASE
# ==============================================================================
title: "Franchini - Concessionnaire Deutz-Fahr"
description: "Concessionnaire officiel Deutz-Fahr. Vente et entretien de matériel agricole neuf et d'occasion à Marches, Drôme."
email: contact@franchini.fr
url: "https://mon-site-web-xi.vercel.app" # URL de production
baseurl: "" # Laisser vide pour la racine du domaine
timezone: Europe/Paris
language: fr
version: "~> 4.3.3" # Doit correspondre à la version dans Gemfile

# ==============================================================================
# CONFIGURATION DU THÈME
# ==============================================================================
theme: minima

# Configuration du thème Minima
minima:
  skin: auto
  skin_mode:
    # Vous pouvez définir des couleurs personnalisées ici
    # Voir https://github.com/jekyll/minima#customization
  social_links:
    email: contact@franchini.fr
    phone: 04 75 47 40 37
    address: "111 av des monts du matin, 26300 Marches"

# ==============================================================================
# CONFIGURATION DE LA CONSTRUCTION (BUILD)
# ==============================================================================
# Dossiers à inclure dans la construction finale
include:
  - _pages
  - _includes
  - _layouts
  - _sass
  - assets
  - .htaccess
  - CNAME
  - robots.txt
  - sitemap.xml
  - .nojekyll

# Fichiers et dossiers à exclure de la construction
exclude:
  # Fichiers système et de cache
  - .git
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - .bundle
  - vendor/
  - Thumbs.db
  - .DS_Store

  # Fichiers de configuration et de développement
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - yarn.lock
  - gulpfile.js
  - node_modules/
  - .babelrc
  - .eslintrc.json
  - .prettierrc
  - .editorconfig
  - .gitattributes
  - .github/
  - .vscode/
  
  # Fichiers de déploiement et documentation
  - netlify.toml
  - vercel.json
  - vercel-build.sh
  - README.md
  - LICENSE
  - CHANGELOG.md
  - Serveur.txt

# Répertoires du site
destination: ./_site
plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
collections_dir: _collections

# Paramètres de build
future: true
incremental: false
permalink: pretty

# ==============================================================================
# PLUGINS ET EXTENSIONS
# ==============================================================================
# Plugins Jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-compose
  - sass-embedded
  - jekyll-redirect-from

# Configuration Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  toc_levels: 1..6

# ==============================================================================
# GESTION DES ASSETS
# ==============================================================================
# Configuration pour jekyll-assets
# La gem 'jekyll-assets' n'est pas listée dans le Gemfile.
# Cette section est probablement inactive.
assets:
  sources:
    - _assets/images
    - _assets/fonts
    - _assets/js
    - _assets/css
  compress: true
  gzip: true
  cache: true
  cache_path: "_cache"
  prefix: "/assets"
  digest: true

# Configuration pour SASS
sass:
  style: compressed
  sass_dir: _sass
  implementation: sass-embedded


# ==============================================================================
# COLLECTIONS
# ==============================================================================
collections:
  pages:
    output: true
    permalink: /:path/

# ==============================================================================
# CONFIGURATION DU CONTENU
# ==============================================================================
# Liens de navigation principaux
navigation:
  - title: Matériel Neuf
    url: /pages/neuf/
    sublinks:
      - title: Matériel Neuf
        url: /pages/neuf/
      - title: Matériel Neuf Disponible
        url: /pages/neuf-disponible/
  - title: Occasions
    url: /pages/occasion/
  - title: Magasin
    url: /pages/magasin/
  - title: Services
    url: /pages/services/
  - title: Contact
    url: /pages/contact/

# Marques de matériel
brands:
  - name: Deutz-Fahr
    logo: /assets/images/brands/deutz-fahr.png
    url: /marques/deutz-fahr
  - name: Stoll
    logo: /assets/images/brands/stoll.png
    url: /marques/stoll
  - name: Kramp
    logo: /assets/images/brands/kramp.png
    url: /marques/kramp
  - name: Kverneland
    logo: /assets/images/brands/kverneland.png
    url: /marques/kverneland

# Liens vers les réseaux sociaux
social_links:
  - name: Facebook
    url: https://www.facebook.com/Franchini26300
    icon: fab fa-facebook-f
  - name: Instagram
    url: https://www.instagram.com/franchini_agricole
    icon: fab fa-instagram
  - name: YouTube
    url: https://www.youtube.com/user/FranchiniAgricole
    icon: fab fa-youtube
  - name: LinkedIn
    url: https://www.linkedin.com/company/franchini-agricole
    icon: fab fa-linkedin-in

# Informations du pied de page
footer:
  contact:
    address: "111 av des monts du matin, 26300 Marches"
    phone: "04 75 47 40 37"
    email: "contact@franchini.fr"

# ==============================================================================
# CONFIGURATION SEO
# ==============================================================================
# Utilisé par le plugin jekyll-seo-tag
social:
  name: Franchini Agricole
  links:
    - https://www.facebook.com/Franchini26300
    - https://www.instagram.com/franchini_agricole
    - https://www.youtube.com/user/FranchiniAgricole
    - https://www.linkedin.com/company/franchini-agricole

# Configuration pour le sitemap
sitemap:
  exclude:
    - "/assets/"
    - "/js/"
    - "/css/"
    - "/images/"
    - "/admin/"
    - "/includes/"

# ==============================================================================
# VALEURS PAR DÉFAUT
# ==============================================================================
defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      permalink: "/:name/"
  - scope:
      path: "" # S'applique à tous les fichiers
    values:
      layout: "default"
      sitemap: true
  - scope:
      path: "assets" # Ne pas appliquer de layout aux assets
    values:
      layout: null
      sitemap: false

# ==============================================================================
# PARAMÈTRES DE DÉVELOPPEMENT LOCAL
# ==============================================================================
# Ces paramètres peuvent être surchargés par un fichier _config_development.yml
dev:
  minify: false
  cache: false
  verbose: true